CREATE DOMAIN FLAG AS CHAR(1) CHECK (VALUE IN ('S','N'));

COMMIT;

ALTER TABLE ITEM ADD FLG_CTRL_ESTQ FLAG DEFAULT 'S' ;
ALTER TABLE ITEM ADD FLG_TAB_PRECO FLAG DEFAULT 'S' ;

COMMIT;

update item set flg_ctrl_estq = 'S', flg_tab_preco = 'S' where 1=1

COMMIT;

